apiVersion: apps/v1
kind: Deployment
metadata:
  name: eatup-backend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: eatup-backend
  template:
    metadata:
      labels:
        app: eatup-backend
    spec:
      containers:
      - name: eatup-backend
        image: eatup-backend:latest
        ports:
        - containerPort: 8000
        env:
        - name: SQLALCHEMY_DATABASE_URI
          value: "sqlite:///./test.db"
        - name: UPLOAD_DIR
          value: "static/uploads"